name: explore_the_world-data

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'explore_the_world/data/**'

env:
  IMAGE_NAME: deepset/elasticsearch-countries-and-capitals

jobs:
  build-push:
    name: Build and Push data image
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Create driver
        run: |
          docker buildx create --use --name multi-builder --platform linux/amd64,linux/arm64

      - name: Build and push amd64 image
        working-directory: explore_the_world/data
        env:
          DATA_IMAGE_PLATFORM: linux/amd64
          DATA_IMAGE_PUSH: true
          HAYSTACK_IMAGE_NAME: deepset/haystack:cpu-v1.11.1
        run: |
          ./build.sh

      - name: Build and push arm64 image
        working-directory: explore_the_world/data
        env:
          DATA_IMAGE_PLATFORM: linux/arm64
          DATA_IMAGE_PUSH: true
          HAYSTACK_IMAGE_NAME: deepset/haystack:cpu-v1.11.1
        run: |
          ./build.sh

      - name: Push manifest
        run: |
          docker manifest create $IMAGE_NAME:latest $IMAGE_NAME:linux_amd64 $IMAGE_NAME:linux_arm64
          docker manifest push $IMAGE_NAME:latest