name: explore_the_world

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'explore_the_world/ui/*'

env:
  IMAGE_NAME: deepset/demo-explore-the-world

jobs:
  build-push:
    name: Build and Push UI image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Create driver
        run: |
          docker buildx create --use --name multi-builder --platform linux/amd64,linux/arm64

      - name: Build and push amd64 image
        working-directory: explore_the_world
        run: |
          docker buildx build --push -o type=docker -t $IMAGE_NAME:linux_amd64 --platform linux/amd64 -f Dockerfile .

      - name: Build and push arm64 image
        working-directory: explore_the_world
        run: |
          docker buildx build --push -o type=docker -t $IMAGE_NAME:linux_arm64 --platform linux/arm64 -f Dockerfile .

      - name: Push manifest
        run: |
          docker manifest create $IMAGE_NAME:latest $IMAGE_NAME:linux_amd64 $IMAGE_NAME:linux_arm64
          docker manifest push $IMAGE_NAME:latest